version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # - pip install awscli
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O sam.zip
      - unzip sam.zip -d sam-installation
      - sudo ./sam-installation/install

  build:
    commands:
      # - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      # - aws configure set default.region $AWS_DEFAULT_REGION
      - sam build
      - sam deploy --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --no-confirm-changeset --no-progressbar

artifacts:
  files: template.yaml
