version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O sam.zip
      - unzip sam.zip -d sam-installation
      - sudo ./sam-installation/install
      - pip install poetry

  build:
    commands:
      # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      # - aws configure set default.region $AWS_DEFAULT_REGION
      - poetry export -C menu_suggester -f requirements.txt --output menu_suggester/src/menu_suggester/requirements.txt --without-hashes
      - poetry export -C paprika_fetcher -f requirements.txt --output paprika_fetcher/src/paprika_fetcher/requirements.txt --without-hashes
      - poetry export -C shared -f requirements.txt --output shared/src/dinner_optimizer_shared/requirements.txt --without-hashes
      - poetry export -C upcoming_reminder -f requirements.txt --output upcoming_reminder/src/upcoming_reminder/requirements.txt --without-hashes
      - poetry export -C user_response_recorder -f requirements.txt --output user_response_recorder/src/user_response_recorder/requirements.txt --without-hashes
      - sam build
      - sam deploy --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --no-confirm-changeset --no-progressbar

artifacts:
  files: template.yaml
